sdk: "/usr/lib/ruby/gems/1.8/gems/rhodes-2.2.6"
sdkversion: 2.2.6
name: SpeedLimitMarker
capabilities: 
- gps
- vibrate
#- pim
#- camera
#- phone
#- bluetooth
#- calendar

version: 1.1
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator4.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.speed_limit_marker
  BundleURLScheme: speed_limit_marker

extensions: ["json", "another-extension"]
#excludedirs: "versions/"

