sdk: "/usr/lib/ruby/gems/1.8/gems/rhodes-2.2.6"
sdkversion: 2.2.6
name: storemanager
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator4.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.storemanager
  BundleURLScheme: storemanager

extensions: ["json", "another-extension"]
excludedirs: "versions/"
